language: php
sudo: false

php:
- 7.1
- 7
- 5.6

env:
  global:
  - DRUPAL_BUILD_DIR=$TRAVIS_BUILD_DIR/../drupal
  - SIMPLETEST_DB=mysql://root:@127.0.0.1/webpack
  - TRAVIS=true
  matrix:
  - DRUPAL_CORE=8.3.x
  - DRUPAL_CORE=8.4.x
  - DRUPAL_CORE=8.5.x

matrix:
  # Don't wait for the allowed failures to build.
  fast_finish: true
  include:
  - php: 7.1
    env:
    - DRUPAL_CORE=8.4.x
  allow_failures:
  # Allow the code coverage report to fail.
  - php: 7.1
    env:
    - DRUPAL_CORE=8.4.x

mysql:
  database: webpack
  username: root
  encoding: utf8

# Cache composer downloads.
cache:
  directories:
  - $HOME/.composer

before_install:
# Disable xdebug.
- phpenv config-rm xdebug.ini

# Determine the php settings file location.
- if [[ $TRAVIS_PHP_VERSION = hhvm* ]];
  then export PHPINI=/etc/hhvm/php.ini;
  else export PHPINI=$HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  fi

# PHP Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated
# and will be removed in a future version. To avoid this warning set
# 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input
# stream instead.
- if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]];
  then echo always_populate_raw_post_data = -1 >> $PHPINI;
  fi;

# Disable the default memory limit.
- echo memory_limit = -1 >> $PHPINI

# Update composer.
- composer self-update

install:
# Create the database.
- mysql -e 'create database webpack'

# Download Drupal 8 core from the Github mirror because it is faster.
- git clone --branch $DRUPAL_CORE --depth 1 https://github.com/drupal/drupal.git $DRUPAL_BUILD_DIR

# Reference the module in the build site.
- ls $DRUPAL_BUILD_DIR
- ls $DRUPAL_BUILD_DIR/..
- cat $DRUPAL_BUILD_DIR/composer.json
- ln -s $DRUPAL_BUILD_DIR/vendor/drupal/webpack $DRUPAL_BUILD_DIR/modules/webpack
- ln -s $DRUPAL_BUILD_DIR/vendor/drupal/npm $DRUPAL_BUILD_DIR/modules/npm

# Copy the customized phpunit configuration file to the core directory so
# the relative paths are correct.
- cp $DRUPAL_BUILD_DIR/modules/webpack/phpunit.xml.dist $DRUPAL_BUILD_DIR/core/phpunit.xml

# Bring in the module dependencies without requiring a merge plugin. The
# require also triggers a full 'composer install'.
- composer --working-dir=$DRUPAL_BUILD_DIR require drush/drush:^9

# Add the github repository to composer and require the module this way to test that too.
- composer config --global github-oauth.github.com "$GITHUB_TOKEN"
- composer --working-dir=$DRUPAL_BUILD_DIR config repositories.repo-name vcs https://github.com/drupal-webpack/webpack
- composer --working-dir=$DRUPAL_BUILD_DIR require drupal/webpack:dev-8.x-1.x#$TRAVIS_COMMIT

script:
- $DRUPAL_BUILD_DIR/vendor/bin/phpunit --configuration $DRUPAL_BUILD_DIR/core/phpunit.xml $TRAVIS_BUILD_DIR;
