<?php

/**
 * Implements hook_library_info_alter().
 */
function webpack_library_info_alter(&$libraries, $extension) {
  foreach ($libraries as &$library) {
    if (isset($library['webpack']) && !empty($library['webpack'])) {
      if (is_array($library['js'])) {
        foreach ($library['js'] as &$js_asset) {
          // Make sure that the JS assets are not preprocessed or minified.
          $js_asset['preprocess'] = FALSE;
          $js_asset['minified'] = TRUE;
        }
      }
    }
  }
}
