<?php

/**
 * Implements hook_library_info_alter().
 */
function webpack_test_libs_library_info_alter(&$libraries, $extension) {
  $t=1;
}

function webpack_test_libs_page_attachments(array &$attachments) {
  // Attach the test libraries unconditionally .
  $attachments['#attached']['library'][] = 'webpack_test_libs/test';
  $attachments['#attached']['library'][] = 'webpack_test_libs/test_header';
}
