<?php

/**
 * Implements hook_page_attachments.
 */
function webpack_test_libs_page_attachments(array &$attachments) {
  // Attach the test libraries unconditionally .
  $attachments['#attached']['library'][] = 'webpack_test_libs/test';
  $attachments['#attached']['library'][] = 'webpack_test_libs/test_header';
  $attachments['#attached']['library'][] = 'webpack_test_libs/my_library';
}

/**
 * Implements hook_webpack_config_alter().
 *
 * @throws \Exception
 */
function webpack_test_libs_webpack_config_alter(&$config) {
  if (!isset($config['output']) || empty($config['output'])) {
    throw new \Exception('Output not found in webpack config.');
  }
}

/**
 * Implements hook_npm_working_dir_alter().
 */
function webpack_test_libs_npm_working_dir_alter(&$cwd) {
  $cwd = DRUPAL_ROOT;
}
